# ======================== PROD PROFILE ========================
server.port=8080

# --- Connections are read from System Environment Variables ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# --- JPA/Hibernate (Safe for Production) ---
# Validates that the entities match the database schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Security & Performance ---
spring.sql.init.mode=never
spring.jpa.show-sql=false
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# --- Logging ---
logging.level.root=INFO
logging.file.name=vbank.log
