-- ===================================================================
-- DDL SCRIPT FOR VBank DATABASE
-- Generated by Hibernate
-- ===================================================================

-- Step 1: Create Tables
CREATE TABLE clients (
                         id bigserial NOT NULL,
                         address varchar(255) NOT NULL,
                         document varchar(255) NOT NULL,
                         email varchar(255) NOT NULL,
                         name varchar(255) NOT NULL,
                         phone varchar(255) NOT NULL,
                         PRIMARY KEY (id)
);

CREATE TABLE accounts (
                          id bigserial NOT NULL,
                          account_number varchar(255) NOT NULL,
                          balance numeric(38,2) NOT NULL,
                          client_id bigint NOT NULL,
                          PRIMARY KEY (id)
);

CREATE TABLE transactions (
                              id bigserial NOT NULL,
                              amount numeric(38,2) NOT NULL,
                              status varchar(255) NOT NULL CHECK (status IN ('PENDING','COMPLETED','FAILED','CANCELLED')),
                              "timestamp" timestamp(6) NOT NULL,
                              type varchar(255) NOT NULL CHECK (type IN ('DEPOSIT','WITHDRAWAL')),
                              account_id bigint NOT NULL,
                              PRIMARY KEY (id)
);

-- Step 2: Add Unique Constraints
ALTER TABLE IF EXISTS clients ADD CONSTRAINT UK_clients_document UNIQUE (document);
ALTER TABLE IF EXISTS clients ADD CONSTRAINT UK_clients_email UNIQUE (email);
ALTER TABLE IF EXISTS clients ADD CONSTRAINT UK_clients_phone UNIQUE (phone);
ALTER TABLE IF EXISTS accounts ADD CONSTRAINT UK_accounts_account_number UNIQUE (account_number);

-- Step 3: Add Foreign Key Constraints
ALTER TABLE IF EXISTS accounts
    ADD CONSTRAINT FK_accounts_to_clients
    FOREIGN KEY (client_id)
    REFERENCES clients;

ALTER TABLE IF EXISTS transactions
    ADD CONSTRAINT FK_transactions_to_accounts
    FOREIGN KEY (account_id)
    REFERENCES accounts;